#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
#
menuentry "Kali Linux from ChatGPT" {
  search --set=root --file=/boot/vmlinuz-6.3.0-kali1-amd64
#  gettext_printf "Kali Linux ChatGPT found ..\n" >&2

#Detect architecture (32-bit or 64-bit)
  if [ "`uname -m`" = "x86_64" ]; then
    set arch=x86_64
#    gettext_printf "64 bit system...\n" >&2
  else
    set arch=i386
#    gettext_printf "32 bit system...\n" >&2
  fi
      
 #For UEFI systems
   if [ -d /sys/firmware/efi ]; then 
  	linux /boot/vmlinuz-6.3.0-kali1-amd64
  	initrd /boot/initrd.img-6.3.0-kali-amd64
   else
#For BIOS Systems
  	linux /boot/vmlinuz-6.3.0-kali1-amd64
  	initrd /boot/initrd.img-6.3.0-kali-amd64
   fi 
}


menuentry "Kali Linux from Bill" {
  search --set=root --file=/boot/vmlinuz-6.3.0-kali1-amd64
  linux /boot/vmlinuz-6.3.0-kali1-amd64
  initrd /boot/initrd.img-6.3.0-kali-amd64
}
