#!/bin/sh
exec tail -n +3 $0

menuentry "Kali Linux" {
    search --set=root --file /kali-linux-is-installed-here

    # Detect architecture (32-bit or 64-bit)
    if [ "`uname -m`" = "x86_64" ]; then
        set arch=x86_64
    else
        set arch=i386
    fi

    # For UEFI systems
    if [ -d /sys/firmware/efi ]; then
        linux /boot/vmlinuz root=UUID=535d47fb-00ce04b6f-a694-6bfcdcf5b520 ro quiet splash $arch
        initrd /boot/initrd.img
    else
        # For BIOS systems
        linux /vmlinuz root=UUID=535d47fb-00ce-4b6f-a694-6bfcdcf5b520 ro quiet splash $arch
        initrd /initrd.img
    fi
}


