umount /mnt/proc
umount /mnt/sbin 
umount /mnt/lib 
umount /mnt/boot 
umount /mnt/media 
umount /mnt/srv
umount /mnt/sys
umount /mnt/dev
umount /mnt/bin
umount /mnt/usr
umount /mnt/lib32
umount /mnt/lib54
umount /mnt/etc
umount /mnt/home
umount /mnt/opt
umount /mnt/root
umount /mnt/sys
